--[[
  Preprocessed flow executor for wrk2.

  Expected artifacts (generated by workdir/preprocess_flow.py):
    workdir/generated/lifecycle_manifest.lua
    workdir/generated/lifecycle_iterations.lua

  Example:
    python3 workdir/preprocess_flow.py --workdir workdir --stage lifecycle
    ./wrk -t2 -c10 -R10 -d10s -s scripts/flow_executor.lua http://localhost:9966

  Optional script args (after --, see SCRIPTING):
    ./wrk ... -s scripts/flow_executor.lua http://localhost:9966/ -- --no-flow-failure-logs
    ./wrk ... -s scripts/flow_executor.lua http://localhost:9966/ -- --flow-failure-logs
]]
---@diagnostic disable: undefined-global

local manifest = dofile("workdir/generated/lifecycle_manifest.lua")
local iterations = dofile("workdir/generated/lifecycle_iterations.lua")

local threads = {}
local setup_thread_counter = 0

local base_headers = {}
local thread_id = 0

local conn_state = {}
local status_by_flow = {}
local failures_by_flow = {}
local step_latency_values_by_flow = {}
local step_latency_dropped_by_flow = {}

local idle_request = nil
-- Shared empty table: never mutate; avoids per-request {} alloc for missing params.
local EMPTY_TABLE = {}

-- Runtime knobs.
local reuse_mode = "wrap" -- wrap | stop_on_exhaustion
local success_mode = "http2xx3xx" -- http2xx3xx | strict_expected
local max_error_logs_per_thread = 50
local max_body_snippet_bytes = 220
local max_raw_step_samples_per_flow = 200

local function inc_status(flow_id, status)
  local key = tostring(flow_id) .. ":" .. tostring(status)
  status_by_flow[key] = (status_by_flow[key] or 0) + 1
end

local function inc_failure(flow_id, reason)
  local key = tostring(flow_id) .. ":" .. tostring(reason)
  failures_by_flow[key] = (failures_by_flow[key] or 0) + 1
end

local function encode_status_map(m)
  local parts = {}
  for k, v in pairs(m) do
    parts[#parts + 1] = k .. "=" .. tostring(v)
  end
  -- Omit sort: cheaper on hot path; order is diagnostic-only.
  return table.concat(parts, ",")
end

local function encode_raw_step_map(m)
  local keys = {}
  for k, _ in pairs(m) do
    keys[#keys + 1] = tostring(k)
  end
  table.sort(keys)
  local lines = {}
  for _, k in ipairs(keys) do
    local vals = m[k]
    if vals and #vals > 0 then
      lines[#lines + 1] = k .. ":" .. table.concat(vals, ",")
    end
  end
  return table.concat(lines, ";")
end

local function encode_number_map(m)
  local keys = {}
  for k, _ in pairs(m) do
    keys[#keys + 1] = tostring(k)
  end
  table.sort(keys)
  local lines = {}
  for _, k in ipairs(keys) do
    lines[#lines + 1] = k .. "=" .. tostring(m[k] or 0)
  end
  return table.concat(lines, ",")
end

local function parse_keyed_csv_line(text, entry_sep, kv_sep)
  local out = {}
  if not text or text == "" then
    return out
  end
  for token in text:gmatch("([^" .. entry_sep .. "]+)") do
    local key, value = token:match("^(.-)" .. kv_sep .. "(.*)$")
    if key and value and key ~= "" then
      out[key] = value
    end
  end
  return out
end

local now_us
do
  local ok, ffi = pcall(require, "ffi")
  if ok then
    ffi.cdef([[
      typedef long time_t;
      typedef long suseconds_t;
      struct timeval {
        time_t tv_sec;
        suseconds_t tv_usec;
      };
      int gettimeofday(struct timeval *tv, void *tz);
    ]])
    local tv = ffi.new("struct timeval")
    now_us = function()
      ffi.C.gettimeofday(tv, nil)
      return (tonumber(tv.tv_sec) * 1000000) + tonumber(tv.tv_usec)
    end
  else
    now_us = function()
      return math.floor(os.clock() * 1000000)
    end
  end
end

local function json_error(msg)
  error("json parse error: " .. msg)
end

local function escape_json_string(s)
  local out = {}
  for i = 1, #s do
    local b = string.byte(s, i)
    if b == 34 then
      out[#out + 1] = '\\"'
    elseif b == 92 then
      out[#out + 1] = "\\\\"
    elseif b == 8 then
      out[#out + 1] = "\\b"
    elseif b == 12 then
      out[#out + 1] = "\\f"
    elseif b == 10 then
      out[#out + 1] = "\\n"
    elseif b == 13 then
      out[#out + 1] = "\\r"
    elseif b == 9 then
      out[#out + 1] = "\\t"
    elseif b < 32 then
      out[#out + 1] = string.format("\\u%04X", b)
    else
      out[#out + 1] = string.char(b)
    end
  end
  return table.concat(out)
end

-- Minimal JSON decoder (byte-oriented; avoids per-codeunit string.sub in tight loops).
local function decode_json(text)
  if text == nil then
    return nil
  end
  local i = 1
  local n = #text

  local function skip_ws()
    while i <= n do
      local b = string.byte(text, i)
      if b == 32 or b == 9 or b == 10 or b == 13 then
        i = i + 1
      else
        break
      end
    end
  end

  local function peek_byte()
    return string.byte(text, i)
  end

  local parse_value

  local function parse_string()
    if peek_byte() ~= 34 then
      json_error("expected string at " .. i)
    end
    i = i + 1
    local out = {}
    while i <= n do
      local b = peek_byte()
      if b == 34 then
        i = i + 1
        if #out == 0 then
          return ""
        end
        return table.concat(out)
      elseif b == 92 then
        i = i + 1
        if i > n then
          json_error("bad escape at end")
        end
        local esc = string.byte(text, i)
        if esc == 34 or esc == 92 or esc == 47 then
          out[#out + 1] = string.char(esc)
        elseif esc == 98 then
          out[#out + 1] = "\b"
        elseif esc == 102 then
          out[#out + 1] = "\f"
        elseif esc == 110 then
          out[#out + 1] = "\n"
        elseif esc == 114 then
          out[#out + 1] = "\r"
        elseif esc == 116 then
          out[#out + 1] = "\t"
        elseif esc == 117 then
          -- Keep \uXXXX escaped as literal; pointers for this workload are not unicode-sensitive.
          local hex = text:sub(i + 1, i + 4)
          if #hex ~= 4 then
            json_error("bad unicode escape at " .. i)
          end
          out[#out + 1] = "\\u" .. hex
          i = i + 4
        else
          json_error("unknown escape at " .. i)
        end
        i = i + 1
      else
        local j = i
        while i <= n do
          b = string.byte(text, i)
          if b == 34 or b == 92 then
            break
          end
          i = i + 1
        end
        if i > j then
          out[#out + 1] = text:sub(j, i - 1)
        end
      end
    end
    json_error("unterminated string")
  end

  local function parse_number()
    local s = i
    local b = peek_byte()
    if b == 45 then
      i = i + 1
    end
    while i <= n do
      b = string.byte(text, i)
      if b and b >= 48 and b <= 57 then
        i = i + 1
      else
        break
      end
    end
    if i <= n and peek_byte() == 46 then
      i = i + 1
      while i <= n do
        b = string.byte(text, i)
        if b and b >= 48 and b <= 57 then
          i = i + 1
        else
          break
        end
      end
    end
    if i <= n then
      b = peek_byte()
      if b == 101 or b == 69 then
        i = i + 1
        if i <= n then
          b = peek_byte()
          if b == 43 or b == 45 then
            i = i + 1
          end
        end
        while i <= n do
          b = string.byte(text, i)
          if b and b >= 48 and b <= 57 then
            i = i + 1
          else
            break
          end
        end
      end
    end
    local num = tonumber(text:sub(s, i - 1))
    if num == nil then
      json_error("bad number at " .. s)
    end
    return num
  end

  local function parse_array()
    if peek_byte() ~= 91 then
      json_error("expected '[' at " .. i)
    end
    i = i + 1
    skip_ws()
    local arr = {}
    if peek_byte() == 93 then
      i = i + 1
      return arr
    end
    while true do
      skip_ws()
      arr[#arr + 1] = parse_value()
      skip_ws()
      local b = peek_byte()
      if b == 44 then
        i = i + 1
      elseif b == 93 then
        i = i + 1
        return arr
      else
        json_error("expected ',' or ']' at " .. i)
      end
    end
  end

  local function parse_object()
    if peek_byte() ~= 123 then
      json_error("expected '{' at " .. i)
    end
    i = i + 1
    skip_ws()
    local obj = {}
    if peek_byte() == 125 then
      i = i + 1
      return obj
    end
    while true do
      skip_ws()
      local k = parse_string()
      skip_ws()
      if peek_byte() ~= 58 then
        json_error("expected ':' at " .. i)
      end
      i = i + 1
      skip_ws()
      obj[k] = parse_value()
      skip_ws()
      local b = peek_byte()
      if b == 44 then
        i = i + 1
      elseif b == 125 then
        i = i + 1
        return obj
      else
        json_error("expected ',' or '}' at " .. i)
      end
    end
  end

  function parse_value()
    skip_ws()
    local b = peek_byte()
    if b == 34 then
      return parse_string()
    elseif b == 123 then
      return parse_object()
    elseif b == 91 then
      return parse_array()
    elseif b == 45 or (b and b >= 48 and b <= 57) then
      return parse_number()
    elseif i + 3 <= n and text:sub(i, i + 3) == "true" then
      i = i + 4
      return true
    elseif i + 4 <= n and text:sub(i, i + 4) == "false" then
      i = i + 5
      return false
    elseif i + 3 <= n and text:sub(i, i + 3) == "null" then
      i = i + 4
      return nil
    end
    json_error("unexpected token at " .. i)
  end

  skip_ws()
  local value = parse_value()
  skip_ws()
  if i <= n then
    json_error("trailing content at " .. i)
  end
  return value
end


local function encode_json(value)
  local t = type(value)
  if t == "nil" then
    return "null"
  elseif t == "boolean" then
    return value and "true" or "false"
  elseif t == "number" then
    return tostring(value)
  elseif t == "string" then
    return '"' .. escape_json_string(value) .. '"'
  elseif t == "table" then
    -- Detect array-like table.
    local is_array = true
    local count = 0
    for k, _ in pairs(value) do
      if type(k) ~= "number" then
        is_array = false
        break
      end
      count = count + 1
    end
    if is_array then
      local parts = {}
      for i = 1, count do
        parts[#parts + 1] = encode_json(value[i])
      end
      return "[" .. table.concat(parts, ",") .. "]"
    end
    local keys = {}
    for k, _ in pairs(value) do
      keys[#keys + 1] = tostring(k)
    end
    table.sort(keys)
    local parts = {}
    for _, k in ipairs(keys) do
      parts[#parts + 1] = encode_json(k) .. ":" .. encode_json(value[k])
    end
    return "{" .. table.concat(parts, ",") .. "}"
  end
  return "null"
end

local function pointer_unescape(token)
  token = token:gsub("~1", "/")
  token = token:gsub("~0", "~")
  return token
end

local function resolve_json_pointer(root, pointer)
  if pointer == "" then
    return root
  end
  if type(pointer) ~= "string" or pointer:sub(1, 1) ~= "/" then
    return nil, "invalid pointer"
  end
  local current = root
  for token in pointer:gmatch("/([^/]*)") do
    token = pointer_unescape(token)
    if type(current) == "table" then
      if current[token] ~= nil then
        current = current[token]
      else
        local idx = tonumber(token)
        if idx and current[idx + 1] ~= nil then
          current = current[idx + 1]
        else
          return nil, "missing token '" .. token .. "'"
        end
      end
    else
      return nil, "cannot dereference non-table"
    end
  end
  return current, nil
end

local function clone(value)
  if type(value) ~= "table" then
    return value
  end
  local out = {}
  for k, v in pairs(value) do
    out[k] = clone(v)
  end
  return out
end

local function shallow_copy(t)
  if type(t) ~= "table" then
    return t
  end
  local out = {}
  for k, v in pairs(t) do
    out[k] = v
  end
  return out
end

local function parse_stage_step_reference(value)
  -- Format: <stage>.<flowId>.<source>#<jsonPointer>
  local stage, flow_id, source, pointer = value:match("^([^.]+)%.([^.]+)%.([^.]+)#(.*)$")
  if not stage then
    return nil
  end
  if source ~= "responseBody" and source ~= "endpoint" then
    return nil
  end
  if pointer == "" then
    pointer = "/"
  end
  if pointer:sub(1, 1) ~= "/" then
    return nil
  end
  return {
    stage = stage,
    flow_id = flow_id,
    source = source,
    pointer = pointer,
  }
end

local function resolve_reference_value(value, response_obj, st)
  if type(value) ~= "string" then
    return value, nil
  end
  if value:sub(1, 1) == "/" then
    if not response_obj then
      return nil, "pointer '" .. value .. "' requires previous response"
    end
    local resolved, err = resolve_json_pointer(response_obj, value)
    if err then
      return nil, err
    end
    return resolved, nil
  end

  local ref = parse_stage_step_reference(value)
  if not ref then
    return value, nil
  end

  if ref.stage ~= manifest.stage then
    return nil, "reference stage mismatch '" .. ref.stage .. "' != '" .. tostring(manifest.stage) .. "'"
  end
  if not st or type(st.step_outputs) ~= "table" then
    return nil, "reference state unavailable"
  end
  local step_out = st.step_outputs[ref.flow_id]
  if type(step_out) ~= "table" then
    return nil, "missing step output for flow '" .. ref.flow_id .. "'"
  end
  local source_obj = step_out[ref.source]
  if source_obj == nil then
    return nil, "missing source '" .. ref.source .. "' for flow '" .. ref.flow_id .. "'"
  end
  local resolved, err = resolve_json_pointer(source_obj, ref.pointer)
  if err then
    return nil, "reference pointer error: " .. err
  end
  return resolved, nil
end

local function substitute_pointers(value, response_obj, st)
  if type(value) == "string" then
    return resolve_reference_value(value, response_obj, st)
  end
  if type(value) ~= "table" then
    return value, nil
  end
  local out = nil
  for k, v in pairs(value) do
    local sv, err = substitute_pointers(v, response_obj, st)
    if err then
      return nil, err
    end
    if sv ~= v then
      if not out then
        out = {}
        for k2, v2 in pairs(value) do
          out[k2] = v2
        end
      end
      out[k] = sv
    end
  end
  return out or value, nil
end

local function url_encode(s)
  s = tostring(s)
  s = s:gsub("\n", "\r\n")
  s = s:gsub("([^%w%-_%.~])", function(c)
    return string.format("%%%02X", string.byte(c))
  end)
  return s
end

local function apply_path_params(path_template, params)
  local out = path_template
  for k, v in pairs(params or {}) do
    local token = "{" .. tostring(k) .. "}"
    out = out:gsub(token, url_encode(v))
  end
  return out
end

local function append_query(path, query)
  if not query then
    return path
  end
  local parts = {}
  for k, v in pairs(query) do
    if v ~= nil then
      parts[#parts + 1] = url_encode(k) .. "=" .. url_encode(v)
    end
  end
  if #parts == 0 then
    return path
  end
  table.sort(parts)
  return path .. "?" .. table.concat(parts, "&")
end

local function make_idle_request()
  local h = shallow_copy(base_headers)
  return wrk.format("GET", "/petclinic/api/owners", h, nil)
end

local function is_success_status(method, status)
  if success_mode == "http2xx3xx" then
    return status < 400
  end

  -- strict_expected mode, heuristic by HTTP verb.
  method = tostring(method or "")
  if method == "GET" then
    return status == 200 or status == 304
  elseif method == "POST" then
    return status == 200 or status == 201 or status == 202 or status == 204
  elseif method == "PUT" or method == "PATCH" then
    return status == 200 or status == 204
  elseif method == "DELETE" then
    return status == 200 or status == 202 or status == 204
  end
  return status < 400
end

local function body_snippet(text)
  if not text or #text == 0 then
    return ""
  end
  local s = tostring(text)
  s = s:gsub("\n", "\\n")
  s = s:gsub("\r", "\\r")
  if #s > max_body_snippet_bytes then
    return s:sub(1, max_body_snippet_bytes) .. "...(truncated)"
  end
  return s
end

local function log_failure(conn_id, st, reason, status, body)
  if not flow_failure_logs_enabled then
    return
  end
  if _G.fe_error_logs_emitted >= max_error_logs_per_thread then
    return
  end

  _G.fe_error_logs_emitted = _G.fe_error_logs_emitted + 1
  local iter_idx = st and st.iteration_index or -1
  local step_idx = st and st.current_step_index or -1
  local flow_id = st and st.current_flow_id or "unknown"
  local method = st and st.current_method or "?"
  local path = st and st.current_path or "?"
  print(string.format(
    "flow_failure thread=%d conn=%d iter=%s step=%s flow=%s method=%s path=%s status=%s reason=%s body=%s",
    thread_id, conn_id, tostring(iter_idx), tostring(step_idx), tostring(flow_id), tostring(method),
    tostring(path), tostring(status or "-"), tostring(reason), body_snippet(body)
  ))
end

local function ensure_conn_state(conn_id)
  local st = conn_state[conn_id]
  if st then
    return st
  end

  st = {
    assigned = false,
    exhausted = false,
    iteration_index = nil,
    step_index = 0,
    last_response = nil,
    last_error = nil,
    current_flow_id = nil,
    current_step_index = nil,
    current_method = nil,
    current_path = nil,
    current_endpoint_params = nil,
    current_step_started_us = nil,
    current_step_key = nil,
    step_outputs = {},
  }
  local cpthread = manifest.wrk2.connections_per_thread
  local start_index = ((thread_id - 1) * cpthread) + conn_id + 1
  st.next_iteration_index = start_index
  conn_state[conn_id] = st
  return st
end

local function claim_next_iteration(conn_id, st)
  if st.exhausted then
    return false
  end

  local raw_index = st.next_iteration_index
  local index = raw_index
  local total = #iterations
  if total == 0 then
    st.exhausted = true
    _G.fe_iterations_exhausted = _G.fe_iterations_exhausted + 1
    return false
  end

  if index > total then
    if reuse_mode == "wrap" then
      index = ((index - 1) % total) + 1
      _G.fe_iterations_reused = _G.fe_iterations_reused + 1
    else
      st.exhausted = true
      _G.fe_iterations_exhausted = _G.fe_iterations_exhausted + 1
      return false
    end
  end

  st.assigned = true
  st.iteration_index = index
  st.step_index = 1
  st.last_response = nil
  st.last_error = nil
  st.current_flow_id = nil
  st.current_step_index = nil
  st.current_method = nil
  st.current_path = nil
  st.current_endpoint_params = nil
  st.current_step_started_us = nil
  st.current_step_key = nil
  st.step_outputs = {}

  _G.fe_iterations_assigned = _G.fe_iterations_assigned + 1
  _G.fe_iterations_started = _G.fe_iterations_started + 1

  st.next_iteration_index = raw_index + manifest.wrk2.connections
  return true
end

local function fail_current_iteration(conn_id, st, reason, status, body)
  _G.fe_iterations_failed = _G.fe_iterations_failed + 1
  _G.fe_non_success_responses = _G.fe_non_success_responses + 1
  inc_failure(st.current_flow_id or "unknown", reason)
  st.last_error = reason
  log_failure(conn_id, st, reason, status, body)
  st.iteration_index = nil
  st.step_index = 0
  st.last_response = nil
  st.current_step_started_us = nil
  st.current_step_key = nil
end

local function complete_current_iteration(st)
  _G.fe_iterations_completed = _G.fe_iterations_completed + 1
  st.iteration_index = nil
  st.step_index = 0
  st.last_response = nil
  st.last_error = nil
  st.current_step_started_us = nil
  st.current_step_key = nil
end

local function record_step_elapsed(st)
  if not st then
    return
  end
  if not st.current_step_started_us or not st.current_step_key then
    return
  end
  local elapsed = now_us() - st.current_step_started_us
  if elapsed < 0 then
    elapsed = 0
  end
  local key = tostring(st.current_step_key)
  local values = step_latency_values_by_flow[key]
  if not values then
    values = {}
    step_latency_values_by_flow[key] = values
  end
  if #values < max_raw_step_samples_per_flow then
    values[#values + 1] = tostring(elapsed)
  else
    step_latency_dropped_by_flow[key] = (step_latency_dropped_by_flow[key] or 0) + 1
    _G.fe_step_raw_samples_dropped = (_G.fe_step_raw_samples_dropped or 0) + 1
  end
  st.current_step_started_us = nil
  st.current_step_key = nil
end

local function prepare_active_iteration(conn_id)
  local st = ensure_conn_state(conn_id)
  if st.iteration_index == nil then
    local ok = claim_next_iteration(conn_id, st)
    if not ok then
      return st, false
    end
  end
  return st, true
end

local function build_request_for_state(conn_id, st)
  local iter = iterations[st.iteration_index]
  local step = iter and iter.steps and iter.steps[st.step_index]
  if not step then
    fail_current_iteration(conn_id, st, "missing_step", nil, nil)
    return nil
  end

  local path_params, err = substitute_pointers(step.pathParameters or EMPTY_TABLE, st.last_response, st)
  if err then
    _G.fe_pointer_resolve_failures = _G.fe_pointer_resolve_failures + 1
    fail_current_iteration(conn_id, st, "path_pointer:" .. err, nil, nil)
    return nil
  end

  local query, qerr = substitute_pointers(step.query or EMPTY_TABLE, st.last_response, st)
  if qerr then
    _G.fe_pointer_resolve_failures = _G.fe_pointer_resolve_failures + 1
    fail_current_iteration(conn_id, st, "query_pointer:" .. qerr, nil, nil)
    return nil
  end

  local headers, herr = substitute_pointers(step.headers or EMPTY_TABLE, st.last_response, st)
  if herr then
    _G.fe_pointer_resolve_failures = _G.fe_pointer_resolve_failures + 1
    fail_current_iteration(conn_id, st, "header_pointer:" .. herr, nil, nil)
    return nil
  end

  local req_body, berr = substitute_pointers(step.requestBody, st.last_response, st)
  if berr then
    _G.fe_pointer_resolve_failures = _G.fe_pointer_resolve_failures + 1
    fail_current_iteration(conn_id, st, "body_pointer:" .. berr, nil, nil)
    return nil
  end

  local final_headers = shallow_copy(base_headers)
  for k, v in pairs(headers or {}) do
    final_headers[k] = tostring(v)
  end

  local body_text = nil
  if req_body ~= nil then
    local ok, encoded = pcall(encode_json, req_body)
    if not ok then
      _G.fe_template_fill_failures = _G.fe_template_fill_failures + 1
      fail_current_iteration(conn_id, st, "body_encode_failed", nil, nil)
      return nil
    end
    body_text = encoded
    if final_headers["Content-Type"] == nil then
      final_headers["Content-Type"] = "application/json"
    end
  end

  local path = apply_path_params(step.pathTemplate, path_params)
  path = append_query(path, query)
  path = "/petclinic/api" .. path

  st.current_flow_id = step.flowId
  st.current_step_index = st.step_index
  st.current_method = step.method
  st.current_path = path
  st.current_endpoint_params = shallow_copy(path_params or EMPTY_TABLE)
  st.current_step_started_us = now_us()
  st.current_step_key = tostring(step.flowId or "unknown")

  return wrk.format(step.method, path, final_headers, body_text)
end

local function finalize_thread_status()
  _G.fe_status_line = encode_status_map(status_by_flow)
  _G.fe_failure_line = encode_status_map(failures_by_flow)
  _G.fe_step_raw_line = encode_raw_step_map(step_latency_values_by_flow)
  _G.fe_step_raw_dropped_line = encode_number_map(step_latency_dropped_by_flow)
end

local function active_iterations()
  local started = _G.fe_iterations_started or 0
  local completed = _G.fe_iterations_completed or 0
  local failed = _G.fe_iterations_failed or 0
  local active = started - completed - failed
  if active < 0 then
    return 0
  end
  return active
end

local function update_status_snapshot()
  _G.fe_active_iterations = active_iterations()
  finalize_thread_status()
end

local function maybe_prepare_or_idle(conn_id)
  local st, ok = prepare_active_iteration(conn_id)
  if not ok then
    return st, nil
  end
  local req = build_request_for_state(conn_id, st)
  return st, req
end

local function request_with_retries(conn_id, retries)
  for _ = 1, retries do
    local st, req = maybe_prepare_or_idle(conn_id)
    if req ~= nil then
      return req
    end
    if st and st.exhausted then
      return idle_request
    end
  end
  return idle_request
end

local function on_success_response(st, parsed)
  if st.current_flow_id then
    st.step_outputs[st.current_flow_id] = {
      responseBody = parsed,
      endpoint = shallow_copy(st.current_endpoint_params or EMPTY_TABLE),
    }
  end
  st.last_response = parsed
  st.step_index = st.step_index + 1
  local iter = iterations[st.iteration_index]
  if iter and st.step_index > #iter.steps then
    complete_current_iteration(st)
  end
end

local function on_non_success_response(conn_id, st, status, body)
  fail_current_iteration(conn_id, st, "http_status", status, body)
end

local function after_response_bookkeeping()
  update_status_snapshot()
end

local function on_decode_response_body(body)
  if not body or #body == 0 then
    return nil
  end
  local ok, decoded = pcall(decode_json, body)
  if ok then
    return decoded
  end
  return nil
end

local function response_flow(conn_id, st, status, body)
  record_step_elapsed(st)
  if st.current_flow_id then
    inc_status(st.current_flow_id, status)
  end
  if is_success_status(st.current_method, status) then
    local parsed = on_decode_response_body(body)
    on_success_response(st, parsed)
  else
    on_non_success_response(conn_id, st, status, body)
  end
end

local function init_runtime_counters()
  _G.fe_iterations_assigned = 0
  _G.fe_iterations_started = 0
  _G.fe_iterations_completed = 0
  _G.fe_iterations_failed = 0
  _G.fe_iterations_reused = 0
  _G.fe_iterations_exhausted = 0
  _G.fe_pointer_resolve_failures = 0
  _G.fe_template_fill_failures = 0
  _G.fe_non_success_responses = 0
  _G.fe_error_logs_emitted = 0
  _G.fe_status_line = ""
  _G.fe_failure_line = ""
  _G.fe_step_raw_line = ""
  _G.fe_step_raw_dropped_line = ""
  _G.fe_step_raw_samples_dropped = 0
  _G.fe_active_iterations = 0
  _G.fe_max_conn_seen = -1
end

function setup(thread)
  setup_thread_counter = setup_thread_counter + 1
  thread:set("flow_thread_id", setup_thread_counter)
  threads[#threads + 1] = thread
end

function init(args)
  local host = wrk.host
  local port = wrk.port
  host = host:find(":") and ("[" .. host .. "]") or host
  host = port and (host .. ":" .. port) or host
  wrk.headers["Host"] = host
  base_headers["Host"] = host
  base_headers["Accept"] = "application/json"

  thread_id = tonumber(flow_thread_id) or 0
  if thread_id <= 0 then
    error("flow_thread_id missing; setup(thread) was not executed")
  end

  for _, a in ipairs(args or {}) do
    if a == "--flow-failure-logs" then
      flow_failure_logs_enabled = true
    elseif a == "--no-flow-failure-logs" then
      flow_failure_logs_enabled = false
    end
  end

  init_runtime_counters()

  idle_request = make_idle_request()
end

function request(conn_id)
  if conn_id > _G.fe_max_conn_seen then
    _G.fe_max_conn_seen = conn_id
  end
  return request_with_retries(conn_id, 3)
end

function response(status, headers, body, conn_id)
  local st = conn_state[conn_id]
  if not st or st.iteration_index == nil then
    return
  end

  response_flow(conn_id, st, status, body)
  after_response_bookkeeping()
end

function done(summary, latency, requests)
  local assigned = 0
  local started = 0
  local completed = 0
  local failed = 0
  local reused = 0
  local exhausted = 0
  local ptr_fail = 0
  local tpl_fail = 0
  local non_success = 0
  local logs_emitted = 0
  local active = 0
  local expected_connections_seen = 0
  local status_lines = {}
  local failure_lines = {}
  local raw_by_flow = {}
  local dropped_by_flow = {}
  local dropped_total = 0

  for idx, thread in ipairs(threads) do
    assigned = assigned + (thread:get("fe_iterations_assigned") or 0)
    started = started + (thread:get("fe_iterations_started") or 0)
    completed = completed + (thread:get("fe_iterations_completed") or 0)
    failed = failed + (thread:get("fe_iterations_failed") or 0)
    reused = reused + (thread:get("fe_iterations_reused") or 0)
    exhausted = exhausted + (thread:get("fe_iterations_exhausted") or 0)
    ptr_fail = ptr_fail + (thread:get("fe_pointer_resolve_failures") or 0)
    tpl_fail = tpl_fail + (thread:get("fe_template_fill_failures") or 0)
    non_success = non_success + (thread:get("fe_non_success_responses") or 0)
    logs_emitted = logs_emitted + (thread:get("fe_error_logs_emitted") or 0)
    active = active + (thread:get("fe_active_iterations") or 0)
    local max_conn = thread:get("fe_max_conn_seen") or -1
    if max_conn >= 0 then
      expected_connections_seen = expected_connections_seen + (max_conn + 1)
    end
    local line = thread:get("fe_status_line")
    if line and line ~= "" then
      status_lines[#status_lines + 1] = string.format("  thread %d status_by_flow: %s", idx, line)
    end
    local fline = thread:get("fe_failure_line")
    if fline and fline ~= "" then
      failure_lines[#failure_lines + 1] = string.format("  thread %d failures_by_flow: %s", idx, fline)
    end
    local raw_line = thread:get("fe_step_raw_line")
    local raw_pairs = parse_keyed_csv_line(raw_line, ";", ":")
    for flow_id, csv in pairs(raw_pairs) do
      if csv ~= "" then
        local prev = raw_by_flow[flow_id]
        if prev and prev ~= "" then
          raw_by_flow[flow_id] = prev .. "," .. csv
        else
          raw_by_flow[flow_id] = csv
        end
      end
    end
    local dropped_line = thread:get("fe_step_raw_dropped_line")
    local dropped_pairs = parse_keyed_csv_line(dropped_line, ",", "=")
    for flow_id, count_text in pairs(dropped_pairs) do
      local inc = tonumber(count_text) or 0
      dropped_by_flow[flow_id] = (dropped_by_flow[flow_id] or 0) + inc
    end
    dropped_total = dropped_total + (thread:get("fe_step_raw_samples_dropped") or 0)
  end

  print("")
  print("--- flow_executor ---")
  print(string.format("iterations_assigned: %d", assigned))
  print(string.format("iterations_started: %d", started))
  print(string.format("iterations_completed: %d", completed))
  print(string.format("iterations_failed: %d", failed))
  print(string.format("iterations_reused: %d", reused))
  print(string.format("iterations_exhausted: %d", exhausted))
  print(string.format("pointer_resolve_failures: %d", ptr_fail))
  print(string.format("template_fill_failures: %d", tpl_fail))
  print(string.format("non_success_responses: %d", non_success))
  print(string.format("error_logs_emitted: %d", logs_emitted))
  print(string.format("active_iterations_at_done: %d", active))
  for _, line in ipairs(status_lines) do
    print(line)
  end
  for _, line in ipairs(failure_lines) do
    print(line)
  end
  local raw_keys = {}
  for k, _ in pairs(raw_by_flow) do
    raw_keys[#raw_keys + 1] = k
  end
  table.sort(raw_keys)
  for _, flow_id in ipairs(raw_keys) do
    print(string.format("step_raw_us %s: %s", flow_id, raw_by_flow[flow_id]))
  end
  local dropped_keys = {}
  for k, _ in pairs(dropped_by_flow) do
    dropped_keys[#dropped_keys + 1] = k
  end
  table.sort(dropped_keys)
  for _, flow_id in ipairs(dropped_keys) do
    print(string.format("step_raw_samples_dropped %s: %d", flow_id, dropped_by_flow[flow_id] or 0))
  end
  print(string.format("step_raw_samples_dropped_total: %d", dropped_total))
  print(string.format("connections_seen: %d", expected_connections_seen))
  print(string.format("partition_ok: %s", (expected_connections_seen > 0 and assigned >= expected_connections_seen) and "true" or "false"))
  print(string.format("accounting_ok: %s", (started >= (completed + failed)) and "true" or "false"))
end

