#!/usr/bin/env python3
"""
Compile flow.yaml + iteration JSON into runtime artifacts for wrk Lua.

Outputs under workdir/generated by default:
  - <stage>_manifest.json
  - <stage>_iterations.json
  - <stage>_manifest.lua
  - <stage>_iterations.lua
"""

from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path
from typing import Any

import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Preprocess flow config/data for wrk Lua executor")
    parser.add_argument("--workdir", default="workdir", help="Directory containing flow.yaml/openapi.yml/data/")
    parser.add_argument("--stage", default="lifecycle", help="Stage name under flow.yaml stages")
    parser.add_argument("--out", default=None, help="Output directory (default: <workdir>/generated)")
    parser.add_argument(
        "--sanitize-control-chars",
        action="store_true",
        help="Optionally replace control characters (U+0000..U+001F except tab/newline/carriage-return) in strings",
    )
    return parser.parse_args()


def parse_wrk2params(text: str) -> dict[str, Any]:
    """
    Parse strings like: '-t2 -c10 -d10s -R10'
    """
    result: dict[str, Any] = {"raw": text}
    for token in text.split():
        if token.startswith("-t"):
            result["threads"] = int(token[2:])
        elif token.startswith("-c"):
            result["connections"] = int(token[2:])
        elif token.startswith("-R"):
            result["rate"] = int(token[2:])
        elif token.startswith("-d"):
            result["duration"] = token[2:]
    if "threads" not in result or "connections" not in result:
        raise ValueError(f"wrk2params must include -t and -c, got: {text}")
    result["connections_per_thread"] = result["connections"] // result["threads"]
    return result


def parse_openapi_operations(openapi_doc: dict[str, Any]) -> dict[str, dict[str, str]]:
    """
    Returns map: operationId -> {method, path}
    """
    out: dict[str, dict[str, str]] = {}
    for path, methods in (openapi_doc.get("paths") or {}).items():
        if not isinstance(methods, dict):
            continue
        for method, spec in methods.items():
            if not isinstance(spec, dict):
                continue
            op_id = spec.get("operationId")
            if op_id:
                out[op_id] = {"method": str(method).upper(), "path": str(path)}
    return out


def to_flow_nodes(stage_cfg: dict[str, Any]) -> dict[str, Any]:
    raw_nodes = stage_cfg.get("flow") or []
    nodes: dict[str, Any] = {}
    entry_nodes: list[str] = []
    reserved = {"operationId", "entrynode", "edges", "endpoint", "method"}

    for item in raw_nodes:
        if not isinstance(item, dict):
            raise ValueError(f"Each flow item must be an object, got: {item!r}")

        # Supports both forms:
        #   - createOwner:
        #       operationId: addOwner
        # and (commented examples):
        #   - createOwner:
        #       endpoint: /x
        #       method: GET
        # Some provided YAML uses invalid indentation for the first form and is
        # parsed by PyYAML as:
        #   {"createOwner": None, "operationId": "...", "entrynode": ...}
        # We normalize that shape here.
        node_keys = [k for k in item.keys() if k not in reserved]
        if len(node_keys) != 1:
            raise ValueError(f"Unable to infer node name from flow item: {item!r}")
        node_name = node_keys[0]
        node_cfg = item.get(node_name)
        if not isinstance(node_cfg, dict):
            node_cfg = {k: v for k, v in item.items() if k != node_name}
        op_id = node_cfg.get("operationId")
        if not op_id:
            raise ValueError(f"Flow node '{node_name}' missing operationId")

        edges = node_cfg.get("edges") or []
        parsed_edges = []
        for edge in edges:
            target = edge.get("to")
            weight = float(edge.get("weight", 0.0))
            parsed_edges.append({"to": target, "weight": weight})

        if node_cfg.get("entrynode"):
            entry_nodes.append(node_name)

        nodes[node_name] = {
            "name": node_name,
            "operationId": op_id,
            "entrynode": bool(node_cfg.get("entrynode", False)),
            "edges": parsed_edges,
        }

    if not entry_nodes:
        raise ValueError("No entrynode=true node found in flow")

    # Validate edge references + weight sums.
    for node in nodes.values():
        edge_sum = 0.0
        for edge in node["edges"]:
            if edge["to"] not in nodes:
                raise ValueError(f"Node '{node['name']}' has edge to unknown node '{edge['to']}'")
            edge_sum += edge["weight"]
        if node["edges"] and not math.isclose(edge_sum, 1.0, rel_tol=1e-9, abs_tol=1e-6):
            raise ValueError(f"Node '{node['name']}' edge weights must sum to 1.0, got {edge_sum}")

    return {"nodes": nodes, "entry_nodes": entry_nodes}


def collect_pointer_fields(value: Any, path: str = "") -> list[dict[str, str]]:
    """
    Find string values that look like JSON pointers (start with '/').
    """
    pointers: list[dict[str, str]] = []
    if isinstance(value, dict):
        for k, v in value.items():
            child_path = f"{path}.{k}" if path else str(k)
            pointers.extend(collect_pointer_fields(v, child_path))
    elif isinstance(value, list):
        for i, v in enumerate(value):
            child_path = f"{path}[{i}]"
            pointers.extend(collect_pointer_fields(v, child_path))
    elif isinstance(value, str):
        if value.startswith("/"):
            pointers.append({"targetPath": path, "pointer": value})
        elif re.match(r"^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.(responseBody|endpoint)#/", value):
            pointers.append({"targetPath": path, "pointer": value})
    return pointers


def normalize_iteration(iter_doc: dict[str, Any], flow_operation_ids: set[str]) -> dict[str, Any]:
    steps = []
    for idx, step in enumerate(iter_doc.get("steps") or []):
        flow_id = step.get("flowId")
        method = str(step.get("method", "")).upper()
        path_template = step.get("pathTemplate")
        if not flow_id or not method or not path_template:
            raise ValueError(f"Invalid step[{idx}] in iteration {iter_doc.get('iterationIndex')}")
        if flow_id not in flow_operation_ids:
            raise ValueError(f"Step flowId '{flow_id}' not present in flow operationIds")

        normalized = {
            "index": idx,
            "flowId": flow_id,
            "method": method,
            "pathTemplate": path_template,
            "pathParameters": step.get("pathParameters") or {},
            "query": step.get("query") or {},
            "headers": step.get("headers") or {},
            "requestBody": step.get("requestBody"),
        }
        normalized["pointerFields"] = {
            "pathParameters": collect_pointer_fields(normalized["pathParameters"]),
            "query": collect_pointer_fields(normalized["query"]),
            "headers": collect_pointer_fields(normalized["headers"]),
            "requestBody": collect_pointer_fields(normalized["requestBody"]),
        }
        steps.append(normalized)

    return {"iterationIndex": int(iter_doc.get("iterationIndex", 0)), "steps": steps}


def sanitize_text(text: str) -> str:
    out = []
    for ch in text:
        code = ord(ch)
        if code < 32 and ch not in ("\t", "\n", "\r"):
            out.append(" ")
        else:
            out.append(ch)
    return "".join(out)


def sanitize_value(value: Any) -> Any:
    if isinstance(value, str):
        return sanitize_text(value)
    if isinstance(value, list):
        return [sanitize_value(v) for v in value]
    if isinstance(value, dict):
        return {k: sanitize_value(v) for k, v in value.items()}
    return value


def lua_quote_string(text: str) -> str:
    escaped = (
        text.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
        .replace('"', '\\"')
    )
    return f'"{escaped}"'


def to_lua(value: Any) -> str:
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return lua_quote_string(value)
    if isinstance(value, list):
        return "{ " + ", ".join(to_lua(v) for v in value) + " }"
    if isinstance(value, dict):
        parts = []
        for k, v in value.items():
            if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", str(k)):
                key = str(k)
            else:
                key = "[" + to_lua(str(k)) + "]"
            parts.append(f"{key} = {to_lua(v)}")
        return "{ " + ", ".join(parts) + " }"
    raise TypeError(f"Unsupported type for lua serialization: {type(value)!r}")


def write_outputs(out_dir: Path, stage: str, manifest: dict[str, Any], iterations: list[dict[str, Any]]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_json = out_dir / f"{stage}_manifest.json"
    iterations_json = out_dir / f"{stage}_iterations.json"
    manifest_lua = out_dir / f"{stage}_manifest.lua"
    iterations_lua = out_dir / f"{stage}_iterations.lua"

    manifest_json.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    iterations_json.write_text(json.dumps(iterations, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    manifest_lua.write_text("return " + to_lua(manifest) + "\n", encoding="utf-8")
    iterations_lua.write_text("return " + to_lua(iterations) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    workdir = Path(args.workdir).resolve()
    stage = args.stage
    out_dir = Path(args.out).resolve() if args.out else (workdir / "generated")

    flow_yaml = workdir / "flow.yaml"
    openapi_yaml = workdir / "openapi.yml"
    data_dir = workdir / "data" / stage

    if not flow_yaml.exists():
        raise FileNotFoundError(flow_yaml)
    if not openapi_yaml.exists():
        raise FileNotFoundError(openapi_yaml)
    if not data_dir.exists():
        raise FileNotFoundError(data_dir)

    flow_doc = yaml.safe_load(flow_yaml.read_text(encoding="utf-8"))
    openapi_doc = yaml.safe_load(openapi_yaml.read_text(encoding="utf-8"))

    stage_cfg = (flow_doc.get("stages") or {}).get(stage)
    if not isinstance(stage_cfg, dict):
        raise ValueError(f"Stage '{stage}' not found in {flow_yaml}")

    flow_info = to_flow_nodes(stage_cfg)
    op_map = parse_openapi_operations(openapi_doc)

    # Ensure operation IDs used by flow exist in OpenAPI.
    flow_op_ids = {node["operationId"] for node in flow_info["nodes"].values()}
    missing_ops = sorted(flow_op_ids - set(op_map.keys()))
    if missing_ops:
        raise ValueError(f"Flow references unknown operationIds in OpenAPI: {missing_ops}")

    wrk_cfg = parse_wrk2params(str(stage_cfg.get("wrk2params", "")).strip())
    manifest = {
        "stage": stage,
        "wrk2": wrk_cfg,
        "openapi_server": ((openapi_doc.get("servers") or [{}])[0].get("url") if openapi_doc.get("servers") else ""),
        "entryNodes": flow_info["entry_nodes"],
        "nodes": flow_info["nodes"],
        "operationMap": op_map,
    }

    iteration_files = sorted(data_dir.glob("iteration-*.json"))
    if not iteration_files:
        raise ValueError(f"No iteration files found under {data_dir}")

    iterations = []
    for fp in iteration_files:
        raw = json.loads(fp.read_text(encoding="utf-8"))
        normalized = normalize_iteration(raw, flow_op_ids)
        if args.sanitize_control_chars:
            normalized = sanitize_value(normalized)
        iterations.append(normalized)

    write_outputs(out_dir, stage, manifest, iterations)
    print(f"Generated artifacts in: {out_dir}")
    print(f"  iterations: {len(iterations)}")
    print(f"  stage: {stage}")


if __name__ == "__main__":
    main()

